### ISSUE TITLE
Problems 2021-8-18

### ISSUE THREAD

**Issue by hecool108** [alexgo-io/alex.js#13]
1 Lend/Borrow-related contracts haven't been deployed completed. Like 

- [x] "yield-token-pool" 
- [x] "token-ayusda",
- [x] "collateral-rebalancing-pool" etc.

2 yield-token-pool's "get-pool-value-in-token"  is declared as a public function instead of read-only, I see some fields on web app needs this to calculate the value, all the public calls will need a popup wallet window, I think it will be annoying for user who simply wants to view some data. 
3 Missing functions 
- [ ] 'get-ltv'

**Comment by fiftyeightandeight** [comment]
@hyossid would you be able to help on (1)? I will look into (2).

**Comment by fiftyeightandeight** [comment]
@MarvinJanssen Hi Marvin, the below function calls `(contract-call? the-token get-symbol)`, where `the-token` is a `ft-trait`. And because a trait doesn't say a function is a read-only or public function, it always defaults to a public function, forcing all functions calling these trait calls public functions.

Would you have any suggestions to get around this?

```
(define-public (get-pool-value-in-token (the-aytoken <yield-token-trait>) (the-token <ft-trait>))
    (let
        (
            (aytoken (contract-of the-aytoken))
            (pool (unwrap! (map-get? pools-data-map { aytoken: aytoken }) invalid-pool-err))
            (balance-token (get balance-token pool))
            (balance-aytoken (get balance-aytoken pool))
            (token-symbol (unwrap! (contract-call? the-token get-symbol) get-symbol-fail-err))
            (token-price (unwrap! (contract-call? .open-oracle get-price oracle-src token-symbol) get-oracle-price-fail-err))
            (balance (unwrap! (contract-call? .math-fixed-point add-fixed balance-token balance-aytoken) math-call-err))
        )

        (contract-call? .math-fixed-point mul-up balance token-price)
    )
)
```

**Comment by MarvinJanssen** [comment]
No way around it for now.

https://github.com/blockstack/stacks-blockchain/issues/1981

**Comment by fiftyeightandeight** [comment]
So part of 2.1. Perhaps we revisit after 2.1 release.

**Comment by hyossid** [comment]
Checked, will deploy after debugging
